# xemantic-neo4j-demo deployment configuration

ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.xemantic.neo4j.demo.ServerKt.server

neo4j:
  uri: ${NEO4J_URI}
  user: ${NEO4J_USER}
  password: ${NEO4J_PASSWORD}
  maxConcurrentSessions: 90
